### ISSUE TITLE
Implement additional features for (Arango)Search

### ISSUE THREAD

**Issue by itsezc** [RienNeVaPlus/type-arango#15]
Arango offers ArangoSearch which can be utilised to create advanced search filters and the likes.

**Comment by RienNeVaPlus** [comment]
Right now you can access [ArangoSearch](https://www.arangodb.com/docs/3.6/aql/functions-arangosearch.html) by using AQL within your routes. But I suppose you have some ideas on how to implement these into the [LIST](https://github.com/RienNeVaPlus/type-arango/blob/master/API.md#routelistschema-roles-summary-options) route? Could you elaborate on these?
