### ISSUE TITLE
Get type support for Attribute schame functions

### ISSUE THREAD

**Issue by JonasHiltl** [RienNeVaPlus/type-arango#21]
I'm having issues with defining schema validation function inside the `@Attribute` decorator. because the returned variable, for example `string => string.email()` does not have a type defined, so it's unclear what functions exist on the object.

Below is an example user entity in which I struggle to define schema validation functions, to for example make attributes required or give a default value.
```typescript
@Document()
export class User extends Entity {
  @Index({
    type: "persistent",
    unique: true,
    deduplicate: true,
  })
  @Attribute((string) => string.lowercase()) //needs to be required
  username!: string;

  @Attribute() //needs to be required
  firstname!: string;

  @Attribute((string) => string.optional()) //can be optional
  lastname: string;

  @Attribute((string) => string.email()) //got from docs example
  email!: string;

  @Attribute((bool) => bool.default(false)) //should default to false if not defined
  emailVerified: boolean;

  @Attribute()
  password!: string, //needs to be required

  @Attribute((string) => string.optional()) //can be optional
  picture: string;

  @Attribute()
  createdAt: Type.DateInsert;

  @Attribute()
  updatedAt: Type.DateUpdate;
}
```
It would be awesome to have some more documentation on how exactly we can provide a `Joi` function inside the `@Attribute` decorator or what the types are from the objects we can access in the decorator.

**Comment by RienNeVaPlus** [comment]
Looks good to me. Keep in mind that schemas are validated only when using CRUD-Routes, the methods `document`, `insert`, `update`, `replace` and `remove` of RouteArg or `save`, `insert`, `replace` & `remove` of an Entity - but not when using a query.

Related:
- [@Attribute(schema?, readers?, writers?)](https://github.com/RienNeVaPlus/type-arango/blob/master/API.md#attributeschema-readers-writers)
- [📜 En-(hanced) Joi](https://github.com/RienNeVaPlus/type-arango/blob/master/API.md#-en-hanced-joi)
- ArangoDB Docs: [Schema validation](https://www.arangodb.com/docs/3.8/foxx-migrating2x-repositories.html#schema-validation)
- and of course the [joi Dokumentation](https://joi.dev/api/?v=12.1.0).
