### ISSUE TITLE
How to set Content-Type Header?

### ISSUE THREAD

**Issue by kapilpipaliya** [RienNeVaPlus/type-arango#22]
How to set `res.setHeader("content-type", "text/html");`? It always return as `Content-Type: application/json; charset=utf-8`

**Comment by RienNeVaPlus** [comment]
Type-arango is optimized to be primarily used with a `application/json` content type.
However, since `v1.5.8` the [response mime](https://www.arangodb.com/docs/3.9/foxx-reference-routers-response.html#type) can be set using the route options:
```ts
  @Route.GET('test', { response: { mime: ['text/html'] } } )
  static TEST(){
    return 1
  }
```
